# Python_Programming_Assignment_008

**Concepts used:-**    
Numpy  
string library  

==============================================================================================================

### 1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

In [68]:
m1 = np.array([[2,3],[4,5]])   # assigning 2x2 matrix into m1

In [69]:
m1.ndim                # checks number of dimentions in an array.

2

In [70]:
m1.shape   # 2 rows and 3 columns

(2, 2)

In [71]:
m2 = np.array([[7,8],[9,1]])   # assigning 2x2 matrix into m2

In [72]:
m2

array([[7, 8],
       [9, 1]])

In [73]:
m1 + m2

array([[ 9, 11],
       [13,  6]])

==============================================================================================================

### 2. Write a Python Program to Multiply Two Matrices?

In [74]:
m1 * m2  # this is just an element wise multiplication

array([[14, 24],
       [36,  5]])

In [75]:
print(m1.shape)
print(m2.shape)

(2, 2)
(2, 2)


In [76]:
# This is an actual multiplication
# number of rows and columns should be equal in both matrixes
m1@m2

array([[41, 19],
       [73, 37]])

==============================================================================================================

### 3. Write a Python Program to Transpose a Matrix?

In [77]:
m = np.array( [ [ [2,3],[4,5],[7,9] ] ] )

In [78]:
m.ndim   #3*2 matrics

3

In [79]:
m.shape

(1, 3, 2)

In [83]:
rows, cols, matrix = m.shape   # single matrix with 3 rows and 2 columns

In [84]:
m

array([[[2, 3],
        [4, 5],
        [7, 9]]])

In [86]:
# Transpose of a matrix
m.transpose()

array([[[2],
        [4],
        [7]],

       [[3],
        [5],
        [9]]])

==============================================================================================================

### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [173]:
s = 'krishna'
l = list(s)
l.sort()
l

['a', 'h', 'i', 'k', 'n', 'r', 's']

In [174]:
s = " krishna lohith "
l = list(s)
l.sort()
l  # sorts in alphabetical order.

[' ',
 ' ',
 ' ',
 'a',
 'h',
 'h',
 'h',
 'i',
 'i',
 'k',
 'l',
 'n',
 'o',
 'r',
 's',
 't']

==============================================================================================================

### 5. Write a Python Program to Remove Punctuation From a String?

In [254]:
import string

def some(s):
    x = ''
    p = set(string.punctuation) 
    for i in s:
        if i not in p:
            x += i
    return x

input_string = "Hello, World! This is a sample string."
c = some(input_string)
print(c)

Hello World This is a sample string


==============================================================================================================