# Python_Programming_Assignment_013

**Topics Covered:-**  
File handling  
CSV  
Numpy  
Strings  

==============================================================================================================

## Question 1:
###  Write a program that calculates and prints the value according to the given formula: 
#### Q = Square root of [(2 * C * D)/H]
### Following are the fixed values of C and H: C is 50. H is 30.
### D is the variable whose values should be input to your program in a comma-separated sequence.
### Example:- Let us assume the following comma separated input sequence is given to the program: 100,150,180
### The output of the program should be:- 18,22,24

In [65]:
import math
C=50
H=30
put = input('Enter values:- ').split(',')
for i in put:
    D = int(i)
    m = math.sqrt( (2* C * D )//H )
    print(round(m))

Enter values:- 100,150,180
18
22
24


In [67]:
import csv
import math

with open('Formula.csv','w') as file:
    writer = csv.writer(file)
    
    writer.writerow([100,150,180])
    
with open('Formula.csv','r') as file:
    reader = csv.reader(file)
    
    for i in reader:
        for j in i:
            D = int(j)
            m = math.sqrt( (2* C * D )//H )
            print(round(m))

18
22
24


==============================================================================================================

## Question 2:
###  Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.
### Note: i=0,1.., X-1; j=0,1,¡Y-1.
###  Example Suppose the following inputs are given to the program: 3,5
### Then, the output of the program should be: [[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

In [95]:
x,y =  map(int, input('Enter x, y:- ').split(','))

result = []

for i in range(x):
    row=[]
    for j in range(y):
        row.append(i*j)
    result.append(row)
print(result)

Enter x, y:- 3,5
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]


In [98]:
# using numpy
import numpy as np

X, Y = map(int, input().split(','))

result = np.zeros((X, Y), dtype=int)
for i in range(X):
    for j in range(Y):
        result[i][j] = i*j

print(result)

3,5
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


==============================================================================================================

## Question 3:
### Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.
### Suppose the following input is supplied to the program: without,hello,bag,world 
### Then, the output should be: bag,hello,without,world

In [133]:
s = "without,hello,bag,world"

In [134]:
s = sorted(s.split(','))

In [135]:
','.join(s)

'bag,hello,without,world'

==============================================================================================================

## Question 4:
### Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.
### Suppose the following input is supplied to the program: hello world and practice makes perfect and hello world again
### Then, the output should be: again and hello makes perfect practice world

In [146]:
s = "hello world and practice makes perfect and hello world again"
t = set(s.split(' '))
t

{'again', 'and', 'hello', 'makes', 'perfect', 'practice', 'world'}

==============================================================================================================

## Question 5:
### Write a program that accepts a sentence and calculate the number of letters and digits. Suppose the following input is supplied to the program:
### hello world! 123
### Then, the output should be: LETTERS 10 DIGITS 3

In [180]:
s = "hello world! 123"
ap = []
digi = []
for i in s:
    if i.isalpha():
        ap.append(i)
    elif i.isdigit():
        digi.append(i)
print('LETTERS :- ', len(ap))
print('DIGITS :- ',len(digi))

LETTERS :-  10
DIGITS :-  3


==============================================================================================================

## Question 6:
A website requires the users to input username and password to register. Write a program to
check the validity of password input by users.
Following are the criteria for checking the password:
1. At least 1 letter between [a-z]
2. At least 1 number between [0-9]
1. At least 1 letter between [A-Z]
3. At least 1 character from [$#@]
4. Minimum length of transaction password: 6
5. Maximum length of transaction password: 12  
Your program should accept a sequence of comma separated passwords and will check them
according to the above criteria. Passwords that match the criteria are to be printed, each
separated by a comma.  
Example  
If the following passwords are given as input to the program:  ABd1234@1,a F1#,2w3E*,2We3345    
Then, the output of the program should be:  ABd1234@1

In [270]:
import re

def q6(s):
    s = s.split(',')
    for i in s :
        if len(i) >=6 and len(i) <12:
            if re.search("[a-z]",i) and re.search('[A-Z]',i) and re.search('[0-9]',i) and re.search('[@#$]',i):
                    print(i)
                    
s = "ABd1234@1,a F1#,2w3E*,2We3345"
q6(s)

ABd1234@1


==============================================================================================================